server:
  port: 8001

spring:
  cloud:
    config:
      server:
        git:
          default-label: feature/loanFeignClient
          uri: https://github.com/GabrielaSoruco/Soruco-PatagoniaTest.git
          search-paths: config-data

  application:
    name: config-service

